# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15tDNNLq8EcwWWkJObNXhCCGSuf7RWNHa

# Proyek Analisis Data: Nama dataset
- Nama: Rahmat Yuli Andika
- Email:rhmt.andika12@gmail.com
- Id Dicoding: Rahmat Yuli Andika

#Menentukan Pertanyaan Bisnis

1. Bagaimana pola penyewaan sepeda harian berubah seiring waktu (bulan dan jam)?
2. Adakah perbedaan dalam frekuensi sewa sepeda harian antara hari kerja (workingday) dan hari libur (holiday)?

#Menyiapkan semua library yang dibutuhkan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

#menginput dataset
import os
for dirname, _, filename in os.walk('/content/kaggle'):
    for filename in filename:
        print(os.path.join(dirname, filename))

"""#Gathering data"""

import os
for dirname, _, filenames in os.walk('/content/kaggle/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

hour = pd.read_csv("/content/kaggle/hour.csv")
print(hour.shape)
hour.head()

day = pd.read_csv("/content/kaggle/day.csv")
print(day.shape)
day.head()

#menghitung jumlah baris setiap DataFrame
print("Jumlah baris di DataFrame day:", day.shape[0])
print("Jumlah baris di DataFrame hour:", hour.shape[0])

"""#menggabungkan data dalam beberapa dataframe
pada proyek ini ada 2 dataframe yang akan digunakan yaitu,day dan hour. keduanya memiliki tabel yang sama tetapi satuan yang berbeda.
"""

bike_sharing = day.merge(hour, on='dteday', how='inner', suffixes=('_daily', '_hourly'))
print(bike_sharing.shape)
# df_product.head()
bike_sharing.loc[bike_sharing["dteday"].isnull()]
bike_sharing.head()

"""#Assessing Data
melakukan pemeriksaan data sebelum melakukan analisis data. Pada tahap ini akan mengecek tipe data, missing value, duplikat data, dan parameter statistik.
"""

#memeriksa DataFrame
hour.info()
day.info()
bike_sharing.info()

"""tidak terdapat data missing value pada setiap kolom bike_sharing"""

#Melihat Duplikasi
print("Jumlah duplikasi: ", bike_sharing.duplicated().sum())
bike_sharing.describe()

"""Jumlah duplikasi:  0

#Exploratory Data Analysis (EDA)
"""

# mendefinisikan fungsi yang akan digunakan untuk EDA
def range(series):
    return series.max() - series.min()

bike_sharing.describe(include="all")

"""#Explore"""

bike_sharing.groupby(by="season_daily").agg({
    "workingday_daily": "count", #menjumlahkan penyewa pada hari kerja berdasarkan hari libur
    "holiday_daily": ["max", "min", "mean", lambda x: x.max() - x.min()]  # Membuat fungsi kustom untuk range
}).sort_values(by=("workingday_daily", "count"), ascending=False)

bike_sharing.groupby(by="season_daily").mnth_daily .nunique()

bike_sharing.groupby(by="season_daily").instant_daily.nunique()

bike_sharing.groupby(by="season_daily").cnt_daily.nunique()

bike_sharing.groupby(by="season_daily").cnt_hourly.nunique()

"""#Mencari Kolerasi

mencari nilai korelasi dari setiap data perhari.
"""

numerical_columns = ["holiday_daily"
 ,"weekday_daily","workingday_daily","temp_daily","atemp_daily","season_daily", "cnt_daily"]
correlation = bike_sharing[numerical_columns].corr()
print(correlation)

"""Jumlah penyewa sepeda memiliki hubungan yang negatif terhadap hari libur.

#Visualization & Explanatory Analysis

1. Bagaimana pola penyewaan sepeda harian berubah seiring waktu (bulan dan jam)?
"""

sns.set_style("whitegrid")
plt.figure(figsize=(12, 6))
sns.lineplot(x="mnth_daily", y="cnt_daily", data=bike_sharing, ci=None)
plt.title("Pola Jumlah Sewa Sepeda Harian Berdasarkan Bulan")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Sewa Sepeda Harian")
plt.show()

"""2.Adakah perbedaan dalam frekuensi sewa sepeda harian antara hari kerja (workingday) dan hari libur (holiday)?"""

plt.figure(figsize=(8, 5))
sns.boxplot(x="workingday_daily", y="cnt_daily", data=bike_sharing)
plt.title("Perbedaan Antara Hari Kerja dan Hari Libur dalam Jumlah Sewa Sepeda Harian")
plt.xlabel("Workingday")
plt.ylabel("Jumlah Sewa Sepeda Harian")
plt.show()

"""#Conclusion

1. Bagaimana pola penyewaan sepeda harian berubah seiring waktu (bulan dan jam)?

Jumlah penyewaan sepeda menunjukkan peningkatan pada bulan September dan Juni. Di sisi lain, peningkatan jumlah penyewaan sepeda terjadi sekitar pukul 8 pagi dan sekitar pukul 5 atau 6 sore jika dilihat dari perspektif jam.

2. Adakah perbedaan dalam frekuensi sewa sepeda harian antara hari kerja (workingday) dan hari libur (holiday)?

Ada peningkatan jumlah penyewaan sepeda pada hari kerja dibandingkan dengan hari libur.
"""

bike_sharing.to_csv("all_data.csv", index=False)